"""Fly.toml generation and management."""

from pathlib import Path

from src.utils.paths import get_project_root


def _get_fly_dir() -> Path:
    """Get path to .fly/ directory where generated fly.toml files are stored."""
    return get_project_root() / ".fly"


def _get_fly_toml_path() -> Path:
    """Get path to the main app fly.toml inside .fly/ directory."""
    return _get_fly_dir() / "fly.toml"


def _fly_toml_exists() -> bool:
    """Check if fly.toml exists in the .fly/ directory."""
    return _get_fly_toml_path().exists()


def _generate_fly_toml(
    app_name: str,
    region: str,
    *,
    dockerfile: str = "Dockerfile",
    internal_port: int = 8000,
) -> str:
    """Generate fly.toml configuration content.

    Args:
        app_name: The Fly.io app name
        region: Primary region for deployment
        dockerfile: Path to Dockerfile relative to the project root.
        internal_port: Port the app listens on

    Returns:
        fly.toml content as string
    """
    # The toml lives at .fly/fly.toml (one level below the project root).
    # flyctl resolves [build].dockerfile relative to the toml file, so we
    # compute the path from .fly/ back up to wherever the Dockerfile is.
    # For the default "Dockerfile" this produces "../Dockerfile", making the
    # toml self-contained and usable with a plain `fly deploy --config .fly/fly.toml`.
    from pathlib import PurePosixPath

    dockerfile_abs = (get_project_root() / dockerfile).resolve()
    toml_relative = PurePosixPath(
        dockerfile_abs.relative_to(get_project_root().resolve())
    )
    # Step back one level from .fly/ to reach the project root.
    toml_dockerfile = f"../{toml_relative}"
    return f'''# Fly.io configuration - Generated by API Forge CLI
# See https://fly.io/docs/reference/configuration/ for reference

app = "{app_name}"
primary_region = "{region}"

[build]
  dockerfile = "{toml_dockerfile}"

[env]
  PORT = "{internal_port}"

[http_service]
  internal_port = {internal_port}
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
'''


def _write_fly_toml(
    app_name: str,
    region: str,
    *,
    dockerfile: str = "Dockerfile",
    internal_port: int = 8000,
    overwrite: bool = False,
) -> bool:
    """Generate and write fly.toml to project root.

    Args:
        app_name: The Fly.io app name
        region: Primary region for deployment
        dockerfile: Path to Dockerfile
        internal_port: Port the app listens on
        overwrite: Whether to overwrite existing file

    Returns:
        True if file was written, False if skipped
    """
    fly_toml_path = _get_fly_toml_path()

    if fly_toml_path.exists() and not overwrite:
        return False

    content = _generate_fly_toml(
        app_name,
        region,
        dockerfile=dockerfile,
        internal_port=internal_port,
    )

    fly_toml_path.parent.mkdir(parents=True, exist_ok=True)
    fly_toml_path.write_text(content)
    return True
