"""``api-forge-cli update`` — pull template improvements via copier.

Why this exists
---------------
The template ships its application code under ``src/`` so the repo stays
directly importable for development. ``post_gen_setup.py`` renames that
directory to the user's chosen ``<package_name>`` after generation and
rewrites every ``from src.X`` import accordingly. ``copier update`` knows
nothing about that rename, so a raw ``copier update`` just re-renders the
template into a fresh ``src/`` next to the user's renamed package and
leaves the project in a half-merged state.

This wrapper does the dance: it temporarily un-renames the package,
reverse-rewrites the imports, runs ``copier update``, and lets the
existing post-gen tasks rename + rewrite back. From Copier's perspective
the working tree looks like a normal post-render checkout, so its
three-way merge has the right inputs and ``.rej`` files / inline
conflict markers only appear for genuine conflicts.

Workflow detail
---------------
``copier update`` itself refuses to run on a dirty git tree. The wrapper
therefore commits its renames as transient ``[copier-update]`` markers so
Copier sees a clean tree, then ``git reset --soft`` back to the user's
original HEAD once the dance finishes. The net effect: the user keeps
their original commit history and the template's new content lands as
staged-but-uncommitted changes ready for review.

Pre-flight refuses if:
- there's no ``.copier-answers.yml`` (not a Copier project);
- the destination isn't a git repo (Copier needs git for the merge);
- the working tree is dirty (the rename + rewrite is destructive);
- a stray ``src/`` already exists alongside the package (probably a
  previous interrupted run that needs manual cleanup).
"""

from __future__ import annotations

import subprocess
import sys
from collections.abc import Callable
from pathlib import Path

import typer
import yaml

from src.cli.shared.console import console

# ---------------------------------------------------------------------------
# Pre-flight helpers
# ---------------------------------------------------------------------------


def _project_root() -> Path:
    """Return the directory containing ``.copier-answers.yml``."""
    cwd = Path.cwd()
    for candidate in (cwd, *cwd.parents):
        if (candidate / ".copier-answers.yml").exists():
            return candidate
    raise FileNotFoundError(
        "No .copier-answers.yml found in the current directory or any parent."
    )


def _load_package_name(answers_path: Path) -> str:
    data = yaml.safe_load(answers_path.read_text()) or {}
    name = data.get("package_name")
    if not name:
        raise ValueError(
            "package_name is missing from .copier-answers.yml — the project "
            "was generated by an older template version."
        )
    return name


def _import_rewrite_helper() -> Callable[..., int]:
    """Locate and import ``scripts/rename_helpers.rewrite_package_references``."""
    scripts_dir = _project_root() / "scripts"
    if not (scripts_dir / "rename_helpers.py").exists():
        raise FileNotFoundError(
            f"scripts/rename_helpers.py not found under {scripts_dir.parent}. "
            "This project may have been generated from an older template "
            "that didn't ship the rewrite helper."
        )
    if str(scripts_dir) not in sys.path:
        sys.path.insert(0, str(scripts_dir))
    from rename_helpers import rewrite_package_references

    return rewrite_package_references


# ---------------------------------------------------------------------------
# Git helpers — keep all git interaction in one place so error handling
# and CWD/quoting are consistent.
# ---------------------------------------------------------------------------


def _git(
    *args: str, cwd: Path, check: bool = True, capture: bool = True
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["git", *args],
        cwd=cwd,
        check=check,
        capture_output=capture,
        text=True,
    )


def _is_git_repo(cwd: Path) -> bool:
    return (
        _git("rev-parse", "--is-inside-work-tree", cwd=cwd, check=False).returncode == 0
    )


def _git_head(cwd: Path) -> str:
    return _git("rev-parse", "HEAD", cwd=cwd).stdout.strip()


def _git_is_dirty(cwd: Path) -> bool:
    return bool(_git("status", "--porcelain", cwd=cwd).stdout.strip())


def _git_commit_all(cwd: Path, message: str) -> None:
    """Stage everything and commit with ``--no-verify``.

    ``--no-verify`` skips the user's pre-commit hooks because we're inside a
    transient state (the rename produces broken-looking imports relative to
    the user's normal layout); hooks that lint imports will reject it.
    """
    _git("add", "-A", cwd=cwd)
    _git("commit", "--no-verify", "-m", message, cwd=cwd)


# ---------------------------------------------------------------------------
# Typer entrypoint
# ---------------------------------------------------------------------------


update_app = typer.Typer(
    name="update",
    help="Pull template improvements via copier.",
    invoke_without_command=True,
    no_args_is_help=False,
)


@update_app.callback(invoke_without_command=True)
def update(
    trust: bool = typer.Option(
        True,
        "--trust/--no-trust",
        help="Pass --trust to copier (required for templates with post-gen hooks).",
    ),
    skip_dirty_check: bool = typer.Option(
        False,
        "--skip-dirty-check",
        help="Allow updates with a dirty working tree (use with caution).",
    ),
) -> None:
    """Run ``copier update`` with the rename dance the template requires."""
    try:
        project_root = _project_root()
    except FileNotFoundError as e:
        console.error(str(e))
        raise typer.Exit(1) from e

    if not _is_git_repo(project_root):
        console.error(
            f"{project_root} is not a git repository. Copier needs git for "
            "its three-way merge — initialise the repo and commit a baseline "
            "first: `git init && git add . && git commit -m 'baseline'`."
        )
        raise typer.Exit(1)

    answers_path = project_root / ".copier-answers.yml"
    try:
        package_name = _load_package_name(answers_path)
    except (ValueError, yaml.YAMLError) as e:
        console.error(str(e))
        raise typer.Exit(1) from e

    pkg_dir = project_root / package_name
    src_dir = project_root / "src"

    if not pkg_dir.exists():
        console.error(
            f"Package directory '{package_name}/' not found at {project_root}. "
            "Is this a freshly cloned project that hasn't been bootstrapped?"
        )
        raise typer.Exit(1)
    if src_dir.exists():
        console.error(
            "A stray 'src/' directory already exists alongside "
            f"'{package_name}/'. This usually means a previous update was "
            "interrupted; resolve it manually before retrying."
        )
        raise typer.Exit(1)

    if not skip_dirty_check and _git_is_dirty(project_root):
        console.error(
            "Working tree is dirty. Commit or stash before updating, or "
            "re-run with --skip-dirty-check (not recommended)."
        )
        raise typer.Exit(1)

    rewrite = _import_rewrite_helper()
    original_head = _git_head(project_root)

    console.info(f"Pre-flight: '{package_name}/' → 'src/' and rewriting imports")
    pkg_dir.rename(src_dir)
    rewrite(project_root, frm=package_name, to="src", verbose=False)

    # Commit the transient state so copier sees a clean tree. The commit
    # is rolled back into the user's original HEAD via ``git reset --soft``
    # at the end so they don't see the marker in their history.
    _git_commit_all(project_root, "[copier-update] transient pre-rename")

    # ``--skip-answered`` keeps copier from re-prompting for questions
    # already in ``.copier-answers.yml``. ``--defaults`` covers questions
    # the *new* template version added since the last update — copier uses
    # the template's default rather than blocking on interactive input.
    # Without both flags, ``copier update`` fails with "Interactive session
    # required" in non-tty contexts (CI, scripts) and prompts annoyingly
    # in a tty even though the answers are already on disk.
    cmd = ["copier", "update", "--skip-answered", "--defaults"]
    if trust:
        cmd.append("--trust")

    console.info(f"Running: {' '.join(cmd)}")
    result = subprocess.run(cmd, cwd=project_root, check=False, capture_output=False)

    if result.returncode != 0:
        console.warn(f"copier update failed (exit {result.returncode}); rolling back")
        _git("reset", "--hard", original_head, cwd=project_root)
        # ``git reset --hard`` restores tracked files but leaves untracked
        # ones alone. Copier may have written new files into ``src/`` after
        # our marker commit but before failing — those would survive the
        # reset and pollute the next run's pre-flight check. Clean them.
        if src_dir.exists():
            import shutil

            shutil.rmtree(src_dir, ignore_errors=True)
        raise typer.Exit(result.returncode)

    # Copier succeeded. Now do the second half of the dance: rename
    # ``src/`` → ``<package_name>/`` and rewrite imports back.
    #
    # Empirically copier may leave the destination in any of three states:
    # (a) only ``src/`` exists (copier wrote there and ran no _tasks in
    #     the destination, or its _tasks were a no-op);
    # (b) only ``<package_name>/`` exists (copier ran _tasks in the
    #     destination and the rename succeeded cleanly);
    # (c) both exist — copier ran _tasks in the destination (renaming
    #     ``src`` → ``<pkg>``) but then wrote more files via template-path
    #     conventions, recreating ``src``. This is the common case for
    #     ``copier update``: ``<pkg>/`` ends up partially populated and
    #     ``src/`` ends up fully populated.
    #
    # ``src/`` is authoritative whenever it exists — those are copier's
    # last writes and reflect the merged template state. If a stale
    # ``<pkg>/`` exists alongside, blow it away first; copier will have
    # written everything it cared about into ``src/``.
    if src_dir.exists():
        if pkg_dir.exists():
            import shutil

            shutil.rmtree(pkg_dir)
        src_dir.rename(pkg_dir)
        rewrite(project_root, frm="src", to=package_name, verbose=False)
    elif not pkg_dir.exists():
        console.error(
            "Neither src/ nor "
            f"{package_name}/ exists after copier update — cannot continue."
        )
        raise typer.Exit(1)
    # else: only pkg_dir exists; copier's destination _tasks did the work.

    # Tree is dirty (post-rename moved files); commit so we can soft-reset.
    if _git_is_dirty(project_root):
        _git_commit_all(project_root, "[copier-update] template merge result")

    # Reset back to the user's original HEAD with all net changes staged.
    # If nothing changed (template at the same commit as last update), the
    # staged set is empty — we still print a clear message.
    _git("reset", "--soft", original_head, cwd=project_root)

    staged = (
        _git("diff", "--cached", "--name-only", cwd=project_root)
        .stdout.strip()
        .splitlines()
    )

    if not staged:
        console.ok("Already up to date — no changes from the template")
        return

    console.ok(f"Update complete: {len(staged)} file(s) changed by the template")
    console.print("\nStaged for review:")
    for path in staged[:20]:
        console.print(f"  [cyan]{path}[/cyan]")
    if len(staged) > 20:
        console.print(f"  ... and {len(staged) - 20} more")
    console.print(
        "\nReview with [cyan]git diff --staged[/cyan]; commit when satisfied "
        "or [cyan]git reset[/cyan] to discard."
    )

    # Surface conflicts that copier left as inline markers or .rej files.
    conflict_files = [
        p
        for p in staged
        if p.endswith(".rej")
        or "<<<<<<< "
        in (
            (project_root / p).read_text(errors="ignore")
            if (project_root / p).exists() and (project_root / p).is_file()
            else ""
        )
    ]
    if conflict_files:
        console.warn(
            f"{len(conflict_files)} file(s) have merge conflicts — "
            "search for `<<<<<<<` markers or .rej files and resolve before committing."
        )
