"""Type stubs for Fly.io controller package.

This file is AUTO-GENERATED by running:
    python -m src.infra.flyio.controller

Do not edit manually. Regenerate after updating FlyCtlController.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any

__all__ = [
    "CommandResult",
    "ManagedPostgresInfo",
    "FlyAppInfo",
    "BackupInfo",
    "FlyCtlController",
    "FlyCtlControllerSync",
]

# =============================================================================
# Data Types (AUTO-EXTRACTED)
# =============================================================================

@dataclass
class CommandResult:
    """Result of a command execution."""

    success: bool
    stdout: str = ""
    stderr: str = ""
    returncode: int = 0

@dataclass
class ManagedPostgresInfo:
    """Information about a Fly Managed Postgres cluster."""

    id: str
    name: str
    region: str
    plan: str
    status: str
    created_at: str = ""
    connection_string: str | None = None

@dataclass
class FlyAppInfo:
    """Information about a Fly.io application."""

    name: str
    organization: str
    status: str
    hostname: str = ""

@dataclass
class BackupInfo:
    """Information about a Fly Managed Postgres backup."""

    id: str
    status: str
    created_at: str
    size_bytes: int = 0

# =============================================================================
# Async Controller
# =============================================================================

class FlyCtlController:
    """Controller for Fly.io operations via flyctl CLI."""

    async def app_create(
        self, name: str, *, org: str | None = None, generate_name: bool = False
    ) -> CommandResult: ...
    async def app_destroy(
        self, app_name: str, *, confirm: bool = False
    ) -> CommandResult: ...
    async def app_info(self, app_name: str) -> FlyAppInfo | None: ...
    async def app_status(self, app_name: str) -> dict[str, Any] | None: ...
    async def apps_list(self, *, org: str | None = None) -> list[FlyAppInfo]: ...
    async def auth_login(self, *, interactive: bool = False) -> CommandResult: ...
    async def auth_logout(
        self,
    ) -> CommandResult: ...
    async def auth_token(
        self,
    ) -> tuple[bool, str]: ...
    async def auth_whoami(
        self,
    ) -> tuple[bool, str]: ...
    async def deploy(
        self,
        *,
        app: str | None = None,
        config: str | None = None,
        dockerfile: str | None = None,
        image: str | None = None,
        primary_region: str | None = None,
        strategy: str | None = None,
        wait_timeout: int | None = None,
        no_cache: bool = False,
        build_only: bool = False,
        cwd: str | None = None,
    ) -> CommandResult: ...
    async def is_authenticated(
        self,
    ) -> bool: ...
    async def is_installed(
        self,
    ) -> bool: ...
    async def logs(
        self, app_name: str, *, region: str | None = None, instance: str | None = None
    ) -> CommandResult: ...
    async def machine_destroy(
        self, app_name: str, machine_id: str, *, force: bool = False
    ) -> CommandResult: ...
    async def machine_run(
        self,
        image: str,
        *,
        app_name: str,
        command: list[str] | None = None,
        entrypoint: str | None = None,
        env: dict[str, str] | None = None,
        region: str | None = None,
        rm: bool = True,
        timeout: int | None = 600,
        capture_output: bool = False,
    ) -> CommandResult: ...
    async def machine_start(self, app_name: str, machine_id: str) -> CommandResult: ...
    async def machine_stop(self, app_name: str, machine_id: str) -> CommandResult: ...
    async def machines_list(self, app_name: str) -> list[dict[str, Any]]: ...
    async def mpg_attach(
        self,
        cluster_id: str,
        app_name: str,
        *,
        database_name: str | None = None,
        variable_name: str = "DATABASE_URL",
    ) -> CommandResult: ...
    async def mpg_backup_create(self, cluster_id: str) -> CommandResult: ...
    async def mpg_backup_list(self, cluster_id: str) -> list[BackupInfo]: ...
    async def mpg_backup_restore(
        self, cluster_id: str, backup_id: str
    ) -> CommandResult: ...
    async def mpg_connect(self, cluster_id: str) -> CommandResult: ...
    async def mpg_connection_string(
        self,
        cluster_id: str,
        *,
        database_name: str | None = None,
        role: str | None = None,
    ) -> tuple[bool, str]: ...
    async def mpg_create(
        self,
        name: str,
        region: str,
        *,
        plan: str = "basic",
        org: str | None = None,
        volume_size: int = 10,
        pg_major_version: int | None = None,
        enable_postgis: bool = False,
    ) -> CommandResult: ...
    async def mpg_destroy(
        self, cluster_id: str, *, confirm: bool = False
    ) -> CommandResult: ...
    async def mpg_detach(self, cluster_id: str, app_name: str) -> CommandResult: ...
    async def mpg_list(
        self, *, org: str | None = None
    ) -> list[ManagedPostgresInfo]: ...
    async def mpg_proxy(
        self, cluster_id: str, *, port: int = 5432
    ) -> CommandResult: ...
    async def mpg_status(self, cluster_id: str) -> ManagedPostgresInfo | None: ...
    async def postgres_attach(
        self, postgres_app: str, app_name: str
    ) -> CommandResult: ...
    async def postgres_connect(self, app_name: str) -> CommandResult: ...
    async def postgres_create(
        self,
        name: str,
        region: str,
        *,
        org: str | None = None,
        volume_size: int | None = None,
        initial_cluster_size: int | None = None,
        vm_cpus: int | None = None,
        vm_cpu_kind: str | None = None,
        vm_memory: int | None = None,
        password: str | None = None,
    ) -> CommandResult: ...
    async def postgres_get_superuser_password(
        self, app_name: str
    ) -> tuple[bool, str]: ...
    async def postgres_list(
        self,
    ) -> list[FlyAppInfo]: ...
    async def regions_list(
        self,
    ) -> list[dict[str, Any]]: ...
    async def scale_count(
        self, app_name: str, count: int, *, region: str | None = None
    ) -> CommandResult: ...
    async def scale_memory(self, app_name: str, memory_mb: int) -> CommandResult: ...
    async def scale_vm(self, app_name: str, vm_size: str) -> CommandResult: ...
    async def secrets_list(self, app_name: str) -> list[str]: ...
    async def secrets_set(
        self, app_name: str, secrets: dict[str, str], *, stage: bool = False
    ) -> CommandResult: ...
    async def secrets_unset(self, app_name: str, names: list[str]) -> CommandResult: ...

# =============================================================================
# Synchronous Wrapper
# =============================================================================

class FlyCtlControllerSync:
    """Synchronous wrapper for FlyCtlController with full type hints."""

    _controller: FlyCtlController

    def __init__(self, controller: FlyCtlController | None = None) -> None: ...
    def app_create(
        self, name: str, *, org: str | None = None, generate_name: bool = False
    ) -> CommandResult: ...
    def app_destroy(self, app_name: str, *, confirm: bool = False) -> CommandResult: ...
    def app_info(self, app_name: str) -> FlyAppInfo | None: ...
    def app_status(self, app_name: str) -> dict[str, Any] | None: ...
    def apps_list(self, *, org: str | None = None) -> list[FlyAppInfo]: ...
    def auth_login(self, *, interactive: bool = False) -> CommandResult: ...
    def auth_logout(
        self,
    ) -> CommandResult: ...
    def auth_token(
        self,
    ) -> tuple[bool, str]: ...
    def auth_whoami(
        self,
    ) -> tuple[bool, str]: ...
    def deploy(
        self,
        *,
        app: str | None = None,
        config: str | None = None,
        dockerfile: str | None = None,
        image: str | None = None,
        primary_region: str | None = None,
        strategy: str | None = None,
        wait_timeout: int | None = None,
        no_cache: bool = False,
        build_only: bool = False,
        cwd: str | None = None,
    ) -> CommandResult: ...
    def is_authenticated(
        self,
    ) -> bool: ...
    def is_installed(
        self,
    ) -> bool: ...
    def logs(
        self, app_name: str, *, region: str | None = None, instance: str | None = None
    ) -> CommandResult: ...
    def machine_destroy(
        self, app_name: str, machine_id: str, *, force: bool = False
    ) -> CommandResult: ...
    def machine_run(
        self,
        image: str,
        *,
        app_name: str,
        command: list[str] | None = None,
        entrypoint: str | None = None,
        env: dict[str, str] | None = None,
        region: str | None = None,
        rm: bool = True,
        timeout: int | None = 600,
        capture_output: bool = False,
    ) -> CommandResult: ...
    def machine_start(self, app_name: str, machine_id: str) -> CommandResult: ...
    def machine_stop(self, app_name: str, machine_id: str) -> CommandResult: ...
    def machines_list(self, app_name: str) -> list[dict[str, Any]]: ...
    def mpg_attach(
        self,
        cluster_id: str,
        app_name: str,
        *,
        database_name: str | None = None,
        variable_name: str = "DATABASE_URL",
    ) -> CommandResult: ...
    def mpg_backup_create(self, cluster_id: str) -> CommandResult: ...
    def mpg_backup_list(self, cluster_id: str) -> list[BackupInfo]: ...
    def mpg_backup_restore(self, cluster_id: str, backup_id: str) -> CommandResult: ...
    def mpg_connect(self, cluster_id: str) -> CommandResult: ...
    def mpg_connection_string(
        self,
        cluster_id: str,
        *,
        database_name: str | None = None,
        role: str | None = None,
    ) -> tuple[bool, str]: ...
    def mpg_create(
        self,
        name: str,
        region: str,
        *,
        plan: str = "basic",
        org: str | None = None,
        volume_size: int = 10,
        pg_major_version: int | None = None,
        enable_postgis: bool = False,
    ) -> CommandResult: ...
    def mpg_destroy(
        self, cluster_id: str, *, confirm: bool = False
    ) -> CommandResult: ...
    def mpg_detach(self, cluster_id: str, app_name: str) -> CommandResult: ...
    def mpg_list(self, *, org: str | None = None) -> list[ManagedPostgresInfo]: ...
    def mpg_proxy(self, cluster_id: str, *, port: int = 5432) -> CommandResult: ...
    def mpg_status(self, cluster_id: str) -> ManagedPostgresInfo | None: ...
    def postgres_attach(self, postgres_app: str, app_name: str) -> CommandResult: ...
    def postgres_connect(self, app_name: str) -> CommandResult: ...
    def postgres_create(
        self,
        name: str,
        region: str,
        *,
        org: str | None = None,
        volume_size: int | None = None,
        initial_cluster_size: int | None = None,
        vm_cpus: int | None = None,
        vm_cpu_kind: str | None = None,
        vm_memory: int | None = None,
        password: str | None = None,
    ) -> CommandResult: ...
    def postgres_get_superuser_password(self, app_name: str) -> tuple[bool, str]: ...
    def postgres_list(
        self,
    ) -> list[FlyAppInfo]: ...
    def regions_list(
        self,
    ) -> list[dict[str, Any]]: ...
    def scale_count(
        self, app_name: str, count: int, *, region: str | None = None
    ) -> CommandResult: ...
    def scale_memory(self, app_name: str, memory_mb: int) -> CommandResult: ...
    def scale_vm(self, app_name: str, vm_size: str) -> CommandResult: ...
    def secrets_list(self, app_name: str) -> list[str]: ...
    def secrets_set(
        self, app_name: str, secrets: dict[str, str], *, stage: bool = False
    ) -> CommandResult: ...
    def secrets_unset(self, app_name: str, names: list[str]) -> CommandResult: ...
